### ISSUE TITLE
Integrating Curvature in the Cost Function

### ISSUE THREAD

**Issue by walkeri** [ParadigmHyperloop/Routes#14]
Currently, the cost function only penalizes the min_curve of the route. We need to take into account the curvature at all points of the route, whether that is through an average or other means.

**Comment by Jarmill** [comment]
Right now the penalty is the L infinity norm. Try out the L1 or L2 norms and see what happens. Also the norm of the derivative of curvature can be interesting to investigate, though it may not be continuous.

**Comment by BlueSpud** [comment]
Implemented with 0241764270639a95d3d700a3c5e85b78b70fa978
